MODEL:
  META_ARCHITECTURE: "UniRef"
  WEIGHTS: "pretrained_models/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  OTA: True
  WITH_MASK_REF: True
  WITH_LANG_REF: True
  LANG_CONFIG:
    FREEZE_TEXT_ENCODER: False
    MODEL_TYPE: "bert-base"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DDETRS:
    IN_FEATURES: ["res3", "res4", "res5"]
    TO_AGNOSTIC: True
    NUM_CLASSES: 1
    NUM_OBJECT_QUERIES: 300
    TWO_STAGE_NUM_PROPOSALS: 300
    DROPOUT: 0.0
    TWO_STAGE: True
    MIXED_SELECTION: True
    LOOK_FORWARD_TWICE: True
    USE_BACKBONE_FEATURE: True
DATASETS:
  TRAIN: ("coco_2017_train", "refcoco-mixed", "fss-1000-train")
  TEST: ("refcoco-unc-val", "fss-1000-val")
SOLVER:
  IMS_PER_BATCH: 16 # batch-per-gpu = 2
  BASE_LR: 0.00002
  STEPS: ()
  MAX_ITER: 30000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 200
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 1, 0.05]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [2, 2, 2]
  USE_RFS: [False, False, False]
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
OUTPUT_DIR: outputs/joint_task_det_rec_fss_r50_16gpu
VERSION: 2
